### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by ogoffart** [sixtyfpsui/sixtyfps#103]
The hello world in the readme is great, but one need a more complete tutorial to introduce the following concepts:

 - Units
 - Layouts
 - Set property / Connect signal from native code
 - Widgets
 - ...

Maybe turn the todo example into a tutorial?

**Comment by ogoffart** [comment]
We have https://sixtyfps.io/blog/memory-game-tutorial.html but we still need to make it in a documentation form.

**Comment by tronical** [comment]
Note: `.60` Code in `.md` files is automatically tested.

**Comment by tronical** [comment]
The tutorial from the blog is now online at http://sixtyfps.io/docs/tutorial/rust/ and http://sixtyfps.io/docs/tutorial/cpp
