### ISSUE TITLE
ComponentHandle API Review

### ISSUE THREAD

**Issue by ogoffart** [sixtyfpsui/sixtyfps#115]
We need to make an API review for `ComponentHandle` and `ComponentWeakHandle`

 - Is the name even good?  `Handle` is not used in rust. `https://github.com/rust-lang/wg-allocators/issues/8#issuecomment-524205326`  So Maybe one should use `ComponentRef`  or ComponentRc`
 - Forcing the developer to downgrade to a weak to capture for signal handler is a footgun 
 - Having to use `ComponentHandle::as_ref()` to use the setter/getter is annoying

**Comment by ogoffart** [comment]
Also `ModelHandle` which exposes its internal.
Maybe should implement `Model` so we can access the model without reaching the Rc in it.   And should it also implement `Iterator`

**Comment by tronical** [comment]
Commit bdebb77f14d40a288fd0003c08ad0867c563103a implements Iterator for Model. For the ComponentHandle we decided to eliminate it in favour of the compiler generating a struct for the exported components that wrap the VRc inside, along with a public API for the properties/signals that allow getting rid of the `as_ref()` calls.

**Comment by tronical** [comment]
Commit ff1d752bc6d173cd51258feff1ce2b9c4a8eed7e and children replace `ComponentHandle` and friends.
