### ISSUE TITLE
Image: keep aspect ratio

### ISSUE THREAD

**Issue by ogoffart** [sixtyfpsui/sixtyfps#127]
We should have a property (the default?)  to keep the aspect ratio when resizing image.
Other possibilities includes cropping to fit, or maybe tiling.

**Comment by vgarleanu** [comment]
Apologies for resurrecting a closed thread, but I believe that crop to fit is a important image fitting strategy. Are there any plans on implementing crop to fit?

**Comment by ogoffart** [comment]
yes, `image-fit: cover;` ([docs](https://releases.slint.dev/1.5.1/docs/slint/src/language/builtins/enums#imagefit))
