### ISSUE TITLE
Better detection of wasm in the sixtyfps-macros to embedd images

### ISSUE THREAD

**Issue by ogoffart** [sixtyfpsui/sixtyfps#130]
Currently, we rely on `std::env::var("TARGET")` in sixtyfps-build/lib.rs to enable the `embed_resources`
but we should be able to set the embed_resources for wasm also when using the macro

**Comment by tronical** [comment]
I'm in favour of defaulting to `embed_resources = true` and rather allow opt-ing out through environment variables.
Either way I guess we're going to need a deployment howto section in the documentation.
