### ISSUE TITLE
cmake: `import`s are not marked as dependencies

### ISSUE THREAD

**Issue by ogoffart** [sixtyfpsui/sixtyfps#135]
In the cmake macro, the `import`s of a .60 file are not marked as dependencies, so the compiler is not re-run if they changes

**Comment by ogoffart** [comment]
Now it works with ninja.

But with other build tool, all the .60 files in the same directory are marked as dependencies.
And the assets are not marked as dependency.

I'll close this issue because it cannot be fixed.

**Comment by tronical** [comment]
Shall I add a note to our docs that we recommend the Ninja backend and change our examples, etc. also to default to using Ninja?

**Comment by ogoffart** [comment]
yes
