### ISSUE TITLE
Implement the `visible` property

### ISSUE THREAD

**Issue by jturcotte** [sixtyfpsui/sixtyfps#141]
This property is assignable but it does nothing for now and could come in handy when developing more complex UIs. Until then I guess that transparent colors can be a workaround.

I can see other properties in the `reserved_property` function. It could be useful to have a warning printed when a reserved but non-implemented property is assigned.

**Comment by ogoffart** [comment]
the "workaround" now is to use `if (condition) : Rectangle { ... }`  expression.
But yeah, visibility might make sense.

**Comment by jturcotte** [comment]
Thanks, I didn't know the language supported this from reading the documentation. Am I guessing right that the element is destroyed when the condition becomes false?

**Comment by ogoffart** [comment]
> Am I guessing right that the element is destroyed when the condition becomes false?

Yes

**Comment by ogoffart** [comment]
One way to implement this would be to Introduce `Opacity { opacity: 50%;  ...`   node in the item graph.
`visible : foo;`  would lower to an `Opacity { opacity: foo ? 1 : 0; }`
