### ISSUE TITLE
Keyboard events

### ISSUE THREAD

**Issue by matklad** [sixtyfpsui/sixtyfps#144]
As far as I understand, keyboard events are not currently exposed via public API. That is, I can not cobble together my own custom LineInput out of Rectangle and a Text.

**Comment by ogoffart** [comment]
That's right, we haven't exposed the keyboard event to the .60 language or to the public API. We intend to do so, but we are unsure how the API should look like.
For example, we don't know if we should expose a big enum of keys similar to `winit::event::VirtualKeyCode` or rather have a string based API or something in the middle.

What would your use-case be? What exactly are you trying to do?

One aspect we definitively one to solve is also the "shortcut" usecase (https://github.com/sixtyfpsui/sixtyfps/issues/102, ok, this issue is not very descriptive) in which we would decoratively declare the list of possible action and their shortcut, Which would be enabled based on the item which has focus.

**Comment by matklad** [comment]
>What would your use-case be? What exactly are you trying to do?

I am in the "I need to implement my own typing tutor" phase of switching to workman layout, so I mostly just messing around. For this use-case, I need to re-implement LineInput such that it highlights mistaken characters and such. I think I have everything I need to render it. For the input, I thing I need:

* an ability to say "this custom element can have keyboard"
* callback on a keypress
* Ability to decode the physical key into the symbol according to the current keymap

**Comment by ogoffart** [comment]
I was thinking maybe along the lines of

```
callback foo_pressed(key_event);
FocusScope {
    key-pressed(event) => { foo_pressed(event) }
    //...
}
```

Then, from rust:

```rust
my_app.on_foo_pressed(| key_event: sixtyfps::KeyEvent | { /* ... */ });
```

But the question is how to design that KeyEvent.
I have been following a bit https://github.com/rust-windowing/winit/issues/753 which is about the same problem.
I'm not really comfortable exposing a huge enum of key code, but maybe that's what we'll have to do.

**Comment by matklad** [comment]
Yeah, I don't have any relevant knowledge in this area. That said, practically speaking, exposing just https://crates.io/crates/keyboard-types under some kind of `unstable` flag seems like a nice solution for while things are in flux.

**Comment by ogoffart** [comment]
We started working on this.

Currently in master you can now have a `FocusScope` that has a `key-pressed` callback, taking a string as a parameter:
```
FocusScope {
    key-pressed(key) => { 
         // not really valid because of unprintable key and other dead key.
         some_text += key;
    }
}
```
https://sixtyfps.io/editor/?load_url=https://raw.githubusercontent.com/sixtyfpsui/sixtyfps/master/tests/cases/examples/key_press.60

The This now take a string as a parameter, and the idea is that most key combinaison can be represented as a string. For example, backspace is "\u{8}" and return would be "\r".
But there are key that might not have a character representation. Also we don't get access to the modifiers (ctrl, alt, ...).
So we'll have to improve on that.  Maybe we can find some escape code for everything using some private codepoint, but that's not great.  
maybe the event should be an object with a `string` property, a `modifiers`  property, and some other properties.

**Comment by matklad** [comment]
Hey, it works!

https://user-images.githubusercontent.com/1711539/105241277-7ca30f00-5b7e-11eb-825a-b8b885a82778.mp4

**Comment by tronical** [comment]
We changed the API a little in the main branch, instead of `key-pressed(key)` it's now `key-pressed(event)`, which is a structure that has a `text` field and `modifiers`, the latter being a struct with `control`/`alt`/`meta`/`shift` booleans.

**Comment by matklad** [comment]
makes sense, but it feels something else broke, as I don't seem to get events at all? See this reverting commit for details: https://github.com/matklad/120wpm/commit/9c3f4aedd410d679f4d02b4b1af1419889759a36

**Comment by tronical** [comment]
Ooops that shouldn’t happen. From the screenshot I assume that you’re on Linux. Is that correct?

Do you know if your build is using Qt?

(I’ll try to debug but just want to sync configs :)

**Comment by matklad** [comment]
Yup, linux and nixos, so there might be all kinds of dynamic library weirdness.  I don't know about Qt)

**Comment by tronical** [comment]
Apologies, commit 4df0334ed20b3a9d455059329f81eaf13e60577b fixes the issue. We were only sending `key-released`, not `key-pressed` for regularly entered characters 🤦

**Comment by matklad** [comment]
Confirm that the fix works, thanks!
