### ISSUE TITLE
Fix and document Path element

### ISSUE THREAD

**Issue by ogoffart** [sixtyfpsui/sixtyfps#146]
Path element is currently broken (the rendering appear to be incorrect in both backend). It needs to be fixed, and also documented.

**Comment by tronical** [comment]
Related Lyon fix needed for relative quadratic paths in SVG: https://github.com/nical/lyon/pull/631

**Comment by tronical** [comment]
Two commits that help with the rendering issues: e2abdff83c7554490c2e6611b04bb90ea4612cbb and 918aab667c5fcedce3b874e8a8c83534872c5275

**Comment by tronical** [comment]
Commit c4df7748db4a1799143687b127978b03efa5df33 adds docs and 6a4f2aa572b7cce4fb931a71993a3f95dd1f4877 adds the two missing sub-elements to match the SVG command set.
