### ISSUE TITLE
Online editor should show warning diagnostics

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#155]
For example when using deprecated properties, the compiler issues a warning diagnostics with hint which new property to use. The online editor should map warning diagnostics to corresponding markers in the Monaco editor.

**Comment by ogoffart** [comment]
The API currently uses exception to report errors.
But we would need maybe to add a property `diagnostics` to the resulting component.

**Comment by ogoffart** [comment]
This is working now
