### ISSUE TITLE
Shadow isn't follow rectangle radius

### ISSUE THREAD

**Issue by neurotok** [sixtyfpsui/sixtyfps#156]
There is something wrong witch combination for border_radius and shadow-drop

![error](http://pingpongcat.com/data/error.png)

I would also love to see the ability to rounded a selected corners of a rectangle, something like a Vec4() value for every corner independently. In Qt to make something like this I had to use border-image which is I guess itself a nice feature to have, especially from the performance stand point.

**Comment by tronical** [comment]
Indeed, that's wrong. I'll take a look at fixing this.

Regarding the individual corners: Do you mean the ability to specify different values for the radius for each corner of the rectangle?

**Comment by neurotok** [comment]
Yes. Like for example I design and implement this tabs for my client

![border image](http://pingpongcat.com/data/border_image.png)

Using border image (the only way to make this in QML that Im aware of) and now he want's to have  colour customization throughout entire GUI, And I'm screwed :/

**Comment by tronical** [comment]
Test case for future reference:

```60
export MyApp := Window {
    width: 200px;
    height: 100px;
    Rectangle {
        width: 100px;
        height: 50px;
        border-radius: 10px;
        background: blue;
        drop-shadow-color: black;
        drop-shadow-offset-x: 10px;
        drop-shadow-offset-y: 10px;
        drop-shadow-blur: 10px;
    }
}
```

**Comment by tronical** [comment]
Ah yes, thanks, that makes sense (the borders). I'll create a new ticket to track that
