### ISSUE TITLE
Flickable eats all mouse events

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#166]
In the following example the flickable eats all mouse events, which it shouldn't:

```
export Demo := Window {
    width:  300px;
    height: 300px;
    Flickable {
        Text {
            text: "Ok";
            TouchArea {
                clicked => { parent.text = "Clicked"; }
            }
        }
    }
}
```

Without the `Flickable` element, the text of the `Text` label changes to "Clicked" when clicking.

**Comment by ogoffart** [comment]
The current situation is now the opposite: the flickable won't react to flick when there is a toucharea within the view under the pointer.

Ideally the flickable could still recognize the gestures
