### ISSUE TITLE
Add support for additional non-printable keys

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#170]
In particular for this ticket, we want

  * F1, F2, etc.
  * Page Up/Down
  * Cursor Up / Down
  * Insert / Delete
 
These need to be mapped and documented.

**Comment by ogoffart** [comment]
This comment mention some code we could use: https://github.com/sixtyfpsui/sixtyfps/issues/638#issuecomment-962135961

**Comment by jturcotte** [comment]
If you need to encode non-printable character keys as obscure codes encoded as Unicode in strings, then please add human-readable aliases so that event handlers don't have to look like this: https://stackoverflow.com/a/9310900/56315

**Comment by ogoffart** [comment]
@jturcotte we will expose some constant string values in the `Keys` namespace, so one will be able to write

```
if (event.text == Keys.arrow-left) {
}
```

Now the questions is how do we define the names of the keys.
I think using the same unicode mapping as apple <https://www.unicode.org/Public/MAPPINGS/VENDORS/APPLE/CORPCHAR.TXT> is a good idea.
For the names, we could re-use these from the W3C spec: https://www.w3.org/TR/uievents-key/#named-key-attribute-values but snake cased.

**Comment by ogoffart** [comment]
PR at https://github.com/sixtyfpsui/sixtyfps/pull/731

**Comment by ogoffart** [comment]
Note that the PR uses camel case for keys, like `Keys.ArrowLeft`
We are unsure if we shouldn't use snake case instead.
