### ISSUE TITLE
@linear-gradient macro causes a compilation error 

### ISSUE THREAD

**Issue by neurotok** [sixtyfpsui/sixtyfps#172]
The simplest linear gradient example

  Rectangle {
      width: 100px;
      height: 100px;
      background: @linear-gradient(90deg, #3f87a6 0%, #ebf8e1 50%, #f69d3c 100%);
  }

causes a compilation error:

 error: Expected 'image-url' after '@'
   --> /home/marcin/60fps/coffe/ui/dial.60:9:18
    |
  9 |     background: @linear-gradient(90deg, #3f87a6 0%, #ebf8e1 50%, #f69d3c 100%);
    |                  ^
  error: Syntax error: expected Semicolon
   --> /home/marcin/60fps/coffe/ui/dial.60:9:18
    |
  9 |     background: @linear-gradient(90deg, #3f87a6 0%, #ebf8e1 50%, #f69d3c 100%);
    |                  ^
  error: Syntax error: expected Identifier
   --> /home/marcin/60fps/coffe/ui/dial.60:9:34
    |
  9 |     background: @linear-gradient(90deg, #3f87a6 0%, #ebf8e1 50%, #f69d3c 100%);
    |                                  ^
  error: Syntax error: expected RParent
   --> /home/marcin/60fps/coffe/ui/dial.60:9:34
    |
  9 |     background: @linear-gradient(90deg, #3f87a6 0%, #ebf8e1 50%, #f69d3c 100%);
    |                                  ^
  error: Syntax error: expected FatArrow
   --> /home/marcin/60fps/coffe/ui/dial.60:9:34
    |
  9 |     background: @linear-gradient(90deg, #3f87a6 0%, #ebf8e1 50%, #f69d3c 100%);
    |                                  ^
  error: Syntax error: expected LBrace
   --> /home/marcin/60fps/coffe/ui/dial.60:9:34
    |
  9 |     background: @linear-gradient(90deg, #3f87a6 0%, #ebf8e1 50%, #f69d3c 100%);
    |                                  ^
  error: Syntax error: expected RBrace
   --> /home/marcin/60fps/coffe/ui/dial.60:9:39
    |
  9 |     background: @linear-gradient(90deg, #3f87a6 0%, #ebf8e1 50%, #f69d3c 100%);
    |                                       ^
  error: Parse error
   --> /home/marcin/60fps/coffe/ui/dial.60:9:39
    |
  9 |     background: @linear-gradient(90deg, #3f87a6 0%, #ebf8e1 50%, #f69d3c 100%);
    |                                       ^

  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CompileError(["Expected \'image-url\' after \'@\'", "Syntax error: expected Semicolon", "Syntax error: expected Identifier", "Syntax error: expected RParent", "Syntax error: expected FatArrow", "Syntax error: expected LBrace", "Syntax error: expected RBrace", "Parse error"])', build.rs:2:43
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

sixtyfps = "0.0.5"
Linux Mint

**Comment by ogoffart** [comment]
Ah yes, @linear-gradient was only added recently.
You can try with the master version:

```toml
 sixtyfps = { git = "https://github.com/sixtyfpsui/sixtyfps" }
```
