### ISSUE TITLE
Failing assertion in `eval.rs` when using boolean expression accessing uninitialised global boolean property to compute color in binding

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#173]
The following test case asserts in `eval.rs`:

```
global Settings := {
    property <bool> test;
}

export Demo := Rectangle {
    width: 300px;
    height: 300px;

    Rectangle {
        background: Settings.test ? red : green;
    }
}
```

results in

`thread 'main' panicked at 'conditional expression did not evaluate to boolean', sixtyfps_runtime/interpreter/eval.rs:636:57`

**Comment by tronical** [comment]
It seems that accessing a boolean property from a global struct like above results in a void, as the following testcase also asserts with `'unsupported ! Void', sixtyfps_runtime/interpreter/eval.rs:619:30`:

```
global Settings := {
    property <bool> test;
}

export Demo := Rectangle {
    width: 300px;
    height: 300px;

    TouchArea {
        clicked => {
                Settings.test = !Settings.test;
        }
    }
}
```

**Comment by tronical** [comment]
This seems related to the fact that the property isn't explicitly initialised. Explicit initialisation appears to make it work.

**Comment by ogoffart** [comment]
Right, global or other `Value` properties are initialized to `Value::Void` and then it fails when trying to convert.
