### ISSUE TITLE
colorized image difference between Qt and GL backend

### ISSUE THREAD

**Issue by ogoffart** [sixtyfpsui/sixtyfps#176]
This screenshot show tests/cases/examples/colored_image.60 (as of commit c7723a23)
Left is the Qt backend, right is the GL backend.

![Screenshot_20210215_210229](https://user-images.githubusercontent.com/959326/107989409-8b8cae00-6fd2-11eb-8e8a-75179e1e0fe4.png)

The differences include the rendering of the border 
(even with the non-colorized image we can see a small difference. Maybe  a difference in gamma correction?)

Another difference is the orange - yellow - green - transparent gradient, the transparency does not look right.

I think Qt is right and GL needs fixes.

**Comment by tronical** [comment]
I submitted what I think fixes the issue. There is the rendering on my machine (macOS).

| Qt | Before the Change | After the Change |
|-|-|-|
| <img width="250" alt="Qt" src="https://user-images.githubusercontent.com/1486/114752165-4bd60e80-9d56-11eb-9e9c-f20a7d690a75.png"> | <img width="250" alt="before" src="https://user-images.githubusercontent.com/1486/114752191-51cbef80-9d56-11eb-80bc-fbcbf44fe95d.png"> | 
<img width="250" alt="after" src="https://user-images.githubusercontent.com/1486/114752209-55f80d00-9d56-11eb-9d22-f23405e9b788.png"> |

**Comment by tronical** [comment]
So there a visual difference between the gradients, particularly visible with the green gradients. It looks like the GL variant is not transparent. This needs further verification.

**Comment by tronical** [comment]
I believe the difference in colorisation output is fixed, the remaining difference in the above example seems to be due to a difference in the way the gradients themselves are rendered. The same gradient rendered separately shows this, as filed in #313.
