### ISSUE TITLE
Slider not releasing mouse control in Widget Gallery Demo

### ISSUE THREAD

**Issue by vivaladav** [sixtyfpsui/sixtyfps#19]
When releasing the mouse button outside the active area (panel delimited by black border), it's still possible to move the slider when moving the mouse.

**Steps to reproduce:**
- left click on the slider
- move mouse outside the active area
- release mouse button
- go back inside the active area
- slider is still following the mouse

**Comment by tronical** [comment]
I can reproduce that, too. Legit bug.

May I ask how you found this project? :-)

**Comment by vivaladav** [comment]
@suy linked this repo in a chat (we all work with Qt).

**Comment by suy** [comment]
And I knew it because @peter-ha "starred" it on Github. ;-)

**Comment by peter-ha** [comment]
... and I knew because @ogoffart sent me the link :)
