### ISSUE TITLE
Add support for opacity

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#198]
Related to #141 this ticket tracks the ability to apply a variable opacity property to elements that applies to the element's contents and all of its children as a whole - not individually.

This would appear to be a reasonable default. If it becomes necessary to apply the opacity only to the element itself and not the children, then one could render that element as a sibling perhaps.

**Comment by ogoffart** [comment]
This is mostly done.
But we still need to support composing opacity the GL backend

**Comment by ogoffart** [comment]
Done
