### ISSUE TITLE
Add the ability to opt into default zero spacing/padding for layouts

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#200]
At the moment the style defines the defaults for spacing/padding in Layouts. We need a way to either

1. Default to zero values for these and conveniently opt into using the defaults provided by the style

2. Provide a way to conveniently opt out of the defaults provided by the style.

There are different options possible, including but not limited to:

 * Provide a "zero" style
 * Provide default properties in the `Window` element that are initialised to the style defaults and that the layouts bind to by default.
 * Provide `StyledVerticalLayout`, etc. elements that explicitly opt into the values coming from the style

**Comment by ogoffart** [comment]
What we're going to do is to have zero padding and spacing for `VerticalLayout` `GridLayout` and `HorizotalLayout`
And we'll add in sixtyfps_widgets.60 a `VerticalBox` `HorizontalBox` and `GridBox` that are wrapper around the layout bug have default values for padding and spacing.
