### ISSUE TITLE
Printer demo: the text on buttons is misaligned

### ISSUE THREAD

**Issue by ogoffart** [sixtyfpsui/sixtyfps#207]

**Comment by tronical** [comment]
As far as I can see this "bug" is visible with the GL as well as with the Qt backend. The font size is set to 16 pixels, and measuring (with a digital ruler) suggests that the extent of the glyphs actually shown on the screen is within that range, so the distance from the upper edge of the 'S' to the lower edge of the 'g'. Still there's a clear difference between the design in Figma and what we're rendering. These are the metrics from Figma:

<img width="604" alt="Screenshot 2021-04-23 at 14 03 19" src="https://user-images.githubusercontent.com/1486/115868416-b533dc80-a43c-11eb-98bf-69e925a1df81.png">

Note how the text box itself is visually centered, but in distance it isn't.

**Comment by tronical** [comment]
So in our implementation of the above design we are trying to replicate the above design. Slightly simplified it is something like this:

```
export Test := Window {
    background: white;

    Rectangle {
        background: #6862e1;
        
        height: 27px; // line-height in the design

        HorizontalLayout {
            padding-top: 5px;

            label := Text {
                text: "Start scanning";
                color: black;
                horizontal-alignment: center;
                vertical-alignment: center;
                font-family: "Noto Sans";
                font-weight: 900;
                font-size: 16px;
            }
        }
    }
}
```

In Figma this is the cantering:

<img width="370" alt="Screenshot 2021-04-23 at 15 01 57" src="https://user-images.githubusercontent.com/1486/115876330-74d95c00-a446-11eb-8bae-32e176fc7d9c.png">

The centering red line nicely let's the 'n' character for example "hang".

In our implementation it looks like this:

<img width="198" alt="Screenshot 2021-04-23 at 15 03 23" src="https://user-images.githubusercontent.com/1486/115876421-95091b00-a446-11eb-9701-b11fadb6f703.png">

The layout gives the `Text` element a height that is based on its reported implicit height, which is the ascent and descent of the font. That is *more* than 16 pixels. Consequently the centering fails visually.

When fixing the height to the font-size (16 px), the `draw_text` will apply the vertical entering correctly

<img width="198" alt="Screenshot 2021-04-23 at 15 04 55" src="https://user-images.githubusercontent.com/1486/115876637-de596a80-a446-11eb-8500-57e0a5ccb0fb.png">

**Comment by tronical** [comment]
There's a "new" misalignment of the text in the printer queue that happens only with the GL backend
![Screenshot_20210423_183353 png](https://user-images.githubusercontent.com/1486/115903031-651c4080-a463-11eb-9c59-e90b638f188e.jpeg)
