### ISSUE TITLE
Mouse wheel support

### ISSUE THREAD

**Issue by Nan1t** [sixtyfpsui/sixtyfps#222]
First of all, thanks for your work! This toolkit looks great and is better than what so far is available for Rust.

I have some suggestion. It would be great if there was an element like `ScrollArea` to handle mouse wheel scrolling and changes some own numeric property to use it in list views, and other scrollable widgets. Because curretly way to scroll a bit inconvenient for desktop applications.

**Comment by ogoffart** [comment]
Thanks for the feature request.
I've made the Flickable internal element handle the wheel events, so this should work for the ScrollArea and the ListView

**Comment by Nan1t** [comment]
Wow, this was fast. Thanks. This works good in online editor and viewer tool, but for some reason it's not compiling in Rust after update to master branch. I've tried to remove generated files and build it from scratch, but nothing.
Error: https://pastebin.com/jsnwnRkE

**Comment by ogoffart** [comment]
`apply_layout` was removed in master.  Looks like this is mixing version of internal crates. For make sure that the, sixtyfps-build and sixtyfps are on the same revision.   how are you loading them in your Cargo.toml ?

**Comment by Nan1t** [comment]
You right. I just forgot to switch sixtyfps-build to git version too. Thanks again. Issue solved.
