### ISSUE TITLE
`debug()` causes vscode preview to fail/freeze

### ISSUE THREAD

**Issue by flukejones** [sixtyfpsui/sixtyfps#225]
Per title. Insert a `debug("wasd");` somewhere in your main .60 file and try to preview the GUI.

**Comment by tronical** [comment]
Hi Luke, we published a new nightly build of the vs code extension (https://marketplace.visualstudio.com/items?itemName=SixtyFPS.sixtyfps-vscode-nightly ) that includes this fix, so if you're using that (make sure the other one is uninstalled), then just restarting vs code should be enough to get the fix. You can also double check in the extension settings by searching for "@installed SixtyFPS" and see that it shows at least version "v2021.5.1713"
