### ISSUE TITLE
Window drag resize constant expansion

### ISSUE THREAD

**Issue by flukejones** [sixtyfpsui/sixtyfps#226]
Trying to think how to describe this.. drag the window edges and the window will do a constant expand until huge. Feels like the mouse movement is being constantly added to window size even after the mouse stops moving.

System: Fedora 34, Gnome on Wayland. Not tested Xorg, I'll write back when I do get time to test it.

**Comment by tronical** [comment]
Is this happening with one of the demos? If yes, which one? Otherwise, do you have a `.60` file that we could try to reproduce this with?

**Comment by flukejones** [comment]
Yes, happens with compiled printer-demo and preview of that also. Tested gallery as well, same issue.

Happens in:
- printer-demo
- gallery (not tested others
- preview
- compiled rust
- 0.0.6 and git sixtyFPS

**Comment by ogoffart** [comment]
I couldn't reproduce the problem using plasma on wayland.

Do you know if you are using the GL backend or the Qt backend?
and if the GL backend, are you using the wayland feature of winit (which is disabled by default)?

(I also tested the GL backend with the wayland feature, and it is completely off, the window size is not correct at all and there is a region of uninitiated graphics memory. But that is another problem)

**Comment by flukejones** [comment]
GL backend I assume, I haven't set the native backend env var.

> and if the GL backend, are you using the wayland feature of winit (which is disabled by default)?

That's certainly off if it's disabled by default. How would I enable it?

**Comment by ogoffart** [comment]
> How would I enable it?

you need to enable the `wayland` feature of the `sixtyfps` crate.
At this point I don't recommend it though, it looked quite buggy when i tried.

**Comment by flukejones** [comment]
I thought I should illustrate what is happening with a video:
https://www.youtube.com/watch?v=4tj7_1FH1YY

To be clear, this happens in all examples too. X11 non-native. I've not tried QT backend.

Doesn't seem to happen with wayland, but that has its own set of issues.

**Comment by ogoffart** [comment]
Thanks for the video.
I still cannot reproduce. I guess i'll have to install Gnome to try that.
What version are you using? is it 0.0.6 or is it from the master branch?

**Comment by ogoffart** [comment]
I've reproduced the problem in Gnome.

**Comment by flukejones** [comment]
Amazing work! Wow this is smooth in wayland now.
