### ISSUE TITLE
iOS: printer demo is very glitchy, sometimes tapping works, sometimes it does not at all

### ISSUE THREAD

**Issue by guruz** [sixtyfpsui/sixtyfps#23]
https://www.sixtyfps.io/demos/printerdemo/

I can go into the fax, but then I can't press any of the numbers.
However sometimes I can.

Maybe making that page mobile friendly (viewport tag etc) and disabling scrolling makes the focus behaviour better? (just a wild guess).

Could also be related to https://github.com/sixtyfpsui/sixtyfps/issues/15

iOS 13.3

**Comment by tronical** [comment]
Making the page more mobile friendly is a very good idea. Still a bit odd that it's flakey for you and it works great for me (using an Xs and iOS version 13.6.1), but hopefully it is just related to the ergonomics.

**Comment by tronical** [comment]
I haven't experienced any glitchiness with new renderer (also not with the old one) and we've tweaked the html a little. I'm closing this for now short of more concrete things that we can do. We're also working on a re-design of the demo itself.
