### ISSUE TITLE
WebAssembly examples are not working

### ISSUE THREAD

**Issue by gamelaster** [sixtyfpsui/sixtyfps#230]
Browser: Microsoft Edge (Chromium)
No errors in console, just white screen and nothing

**Comment by tronical** [comment]
Yeah, this must've happened just a few minutes ago as I pushed a change that accidentally broke them. I'll push a fix shortly.

**Comment by tronical** [comment]
The fixed demos will be online in ~20 minutes

**Comment by gamelaster** [comment]
What a coincidence that I wanted to try examples just when it get broken 😁 anyway, looking forward to try your platform, it looks very promising and good! 😊
