### ISSUE TITLE
Compile master error in nightly-x86_64-pc-windows-msvc

### ISSUE THREAD

**Issue by happydpc** [sixtyfpsui/sixtyfps#253]
These are the error info:

error[E0277]: the trait bound `lyon_path::Event<Point2D<f32, UnknownUnit>, Point2D<f32, UnknownUnit>>: TightBoundingRect` is not satisfied
   --> sixtyfps_runtime\corelib\graphics\path.rs:282:43
    |
282 |                 viewbox.unwrap_or_else(|| lyon_algorithms::aabb::bounding_rect(self.iter()));
    |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `TightBoundingRect` is not implemented for `lyon_path::Event<Point2D<f32, UnknownUnit>, Point2D<f32, UnknownUnit>>`
    |
   ::: C:\Users\Administrator\.cargo\git\checkouts\lyon-818d449ae51d8382\9b4437a\crates\algorithms\src\aabb.rs:69:10
    |
69  |     Evt: TightBoundingRect,
    |          ----------------- required by this bound in `bounding_rect`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `sixtyfps-corelib`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0277]: the trait bound `lyon_path::builder::WithSvg<lyon_path::path::Builder>: lyon_svg::lyon_path::builder::SvgPathBuilder` is not satisfied
  --> sixtyfps_compiler\passes\compile_paths.rs:77:57
   |
77 |             let path = lyon_svg::path_utils::build_path(path_builder, &commands);
   |                                                         ^^^^^^^^^^^^ the trait `lyon_svg::lyon_path::builder::SvgPathBuilder` is not implemented for `lyon_path::builder::WithSvg<lyon_path::path::Builder>`
   |
  ::: C:\Users\Administrator\.cargo\git\checkouts\lyon-818d449ae51d8382\9b4437a\crates\svg\src\path_utils.rs:35:14
   |
35 |     Builder: SvgPathBuilder + Build,
   |              -------------- required by this bound in `build_path`

error[E0277]: the trait bound `lyon_path::builder::WithSvg<lyon_path::path::Builder>: lyon_svg::lyon_path::builder::Build` is not satisfied
  --> sixtyfps_compiler\passes\compile_paths.rs:77:57
   |
77 |             let path = lyon_svg::path_utils::build_path(path_builder, &commands);
   |                                                         ^^^^^^^^^^^^ the trait `lyon_svg::lyon_path::builder::Build` is not implemented for `lyon_path::builder::WithSvg<lyon_path::path::Builder>`
   |
  ::: C:\Users\Administrator\.cargo\git\checkouts\lyon-818d449ae51d8382\9b4437a\crates\svg\src\path_utils.rs:35:31
   |
35 |     Builder: SvgPathBuilder + Build,
   |                               ----- required by this bound in `build_path`

error[E0277]: the trait bound `lyon_path::builder::WithSvg<lyon_path::path::Builder>: lyon_svg::lyon_path::builder::Build` is not satisfied
  --> sixtyfps_compiler\passes\compile_paths.rs:77:24
   |
77 |             let path = lyon_svg::path_utils::build_path(path_builder, &commands);
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `lyon_svg::lyon_path::builder::Build` is not implemented for `lyon_path::builder::WithSvg<lyon_path::path::Builder>`

**Comment by ogoffart** [comment]
Is this a new error? (eg, Have you been successfully compiling SixtyFPS before?)
Try calling `cargo upgrade`
It looks like different version of lyon_path are in use.

**Comment by ogoffart** [comment]
I just pushed commit 0d09f69, maybe it helps.

**Comment by ogoffart** [comment]
I believe this must be fixed.
