### ISSUE TITLE
Invalid command in Path does not produce an error

### ISSUE THREAD

**Issue by ogoffart** [sixtyfpsui/sixtyfps#262]
I'd expect an error when the commands is not a valid command, but right now it doesn't produce an error
```
Example := Window {
  Path {
    width: 100px;
    height: 100px;
    commands: "hello world";
    stroke: red;
    stroke-width: 1px;
  }
}
```

**Comment by tronical** [comment]
This appears to be rooted in Lyon's `build_path()` function not forwarding errors.
