### ISSUE TITLE
Rust Docs: Add support for Syntax Highlighting of .60 code snippets

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#282]
The `.60` code blocks in the Rust documentation are not syntax highlighted at the moment. Perhaps it would be possible to re-use the .60 highlight.js module, that is also used in the mdbook for the tutorial, and apply syntax highlighting this way.

**Comment by ogoffart** [comment]
Note that we inject some JS in the rust documentation via the `api/sixtyfps-rs/sixtyfps-docs-integration.html` and that the same file is injected in the C++ documentation.
So perhaps the same solution applies for #282 and #281
