### ISSUE TITLE
Make it possible to define constants

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#29]
I would like the ability to share constants or perhaps properties across different components, such as settings like common colours.

One such way would be to have a `const` keyword in a `.60` file, which is part of the regular lookup process but results in those values being inlined:

```
export const <color> DefaultActiveColor : black;
const <string> DefaultName = "ok";
const <length> DefaultSize = 24lx;

export Button := Rectangle {
    const <string> foo : "hello"
    color: DefaultActiveColor;
}
```

```
import * as Colors from "theme_colors.60";

Rectangle {
    color: Colors.DefaultActiveColor;
}
```

Acceptance Criteria: A way of sharing common constants across different components without duplicating them. This also needs to be documented in the language reference.

**Comment by ogoffart** [comment]
One can use properties on a global object for that.
