### ISSUE TITLE
C++ Value API: add constructor / accessor from and to Image

### ISSUE THREAD

**Issue by ZEPORATH** [sixtyfpsui/sixtyfps#350]
My code fails to compile for below line of code: 
```
        auto imageObj = sixtyfps::Image::load_from_path(icon_image);
        sixtyfps::interpreter::Struct s;
        s.set_field("name", Value(name));
        s.set_field("floor_no", Value(floor_no));
        s.set_field("icon", Value(imageObj));
```
error: no matching function for call to ‘sixtyfps::interpreter::Value::Value(sixtyfps::Image&)’

**Comment by ogoffart** [comment]
I took the liberty to rewrite the title.

In C++, the conversion between sixtyfps::interpreter::Value and sixtyfps::Image are missing.  (Also missing in the Rust enum)
