### ISSUE TITLE
Please change the free license to LGPL

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [sixtyfpsui/sixtyfps#373]
I'm new to this library, and it seems like it has good ideas. The most important factor for this library to grow is to have a license that can be freely used even in Linux for everyone. With GPL, this library will be feared because everyone will have to make their code open source. Especially that GPL "infects" all other libraries used in a project and forces them to be open source. However, you can still get all the benefits of the commercial license even with LGPL. Please consider that.

**Comment by joseluis** [comment]
Yeah, the fact that anything that you create that links [even dynamically](https://www.gnu.org/licenses/gpl-faq.en.html#GPLStaticVsDynamic) to this library must also be licensed as GPL-3 is a deal breaker for me. Specially coming from the Rust ecosystem where 99% is dual licensed Apache 2 + MIT. It's a shame because otherwise the project looks very promising.

**Comment by ogoffart** [comment]
The license is GPL on purpose.
We hope to get revenue from SixtyFPS. The GPL is a good fit for open-soure users.
People who don't want to open-source their product, will be able to obtain a commercial license.
We haven't finalized yet the exact pricing model but hope to be something affordable.

**Comment by TheQuantumPhysicist** [comment]
You're mistaken, my man. Allow me to explain. You're supporting a small set of open source developers. Often times I see projects that have to keep parts of their code closed because of licensing issues. Right now, everyone who has any segment of their code with a license incompatible with GPL, will not be able to use your library. Notice: They **won't** be able to use your library. 

Here's why GPL is useless for you to make money: Any company that will use your code, and keeps it internal, they still have the right to use your code without making the code open source. On the other hand, if any company uses your library and want to make users benefit from it, they will anyway be unable to do that because they can't make money out of your library, because your free license is restricted to "non-commercial use". After all, all you want is to prevent people making money without you being part of it, right?

I often recommend to library maintainers to think of it this way: "What is it that you're afraid to happen?" You want more people to use your library. You want even more companies to use your library and get "hooked" with the beauty of your library, per se, which will give them an incentive to consider buying a license. Often companies that I worked for, anyone who saw "GPL" will just dismiss that library. No questions asked. Do you really want that? People often start using libraries for free, then they pay for them when they succeed. All those people won't use your library because of GPL. I bet you'll lose more money than you'll make by restricting it.

It's up to you. Consider my view in your discussions. After all, no company is gonna make money out of your library without paying you if you clearly put it in the license as "non-commercial".

Best of luck.

**Comment by tronical** [comment]
> It's up to you. Consider my view in your discussions. After all, no company is gonna make money out of your library without paying you if you clearly put it in the license as "non-commercial".

Thank you for your input - it is appreciated. In our past careers we've had a very positive experience with the model that we've chosen for this project.

> Best of luck.

Thank you!
