### ISSUE TITLE
Add `sixtyfps::Image::load_from_data`

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#387]
The current Rust API supports creating an image from a path using `load_from_path`, but for certain use-cases (see for example the discussion in #381), we want to offer the ability to use an external software rasteriser to create images and feed them into SixtyFPS by creating a `sixtyfps::Image`.

The raises the question: What's the signature of `load_from_data(...)` in Rust, C++ and JavaScript? What's the API to represent incoming image data?

We know already that we're going to have to make a copy of the data, so a reference that's just valid for the life-time of the function call is fine. Although we could consider an API that allows passing ownership, along with a "dealloc" function pointer.

For C++ we can probably settle for a lower-level API for now (`FormatEnum format, const unsigned char *data, size_t width, size_t height, size_t bytes_per_line`) and later overload with more functions, and `FormatEnum` being just something like `enum class ImageFormat { ARGB32 };` for now.

For JavaScript, perhaps we can initially also settle for a low-level API, expecting an object that resembles [`ImageData`](https://developer.mozilla.org/en-US/docs/Web/API/ImageData). Currently we are not exposing `sixtyfps::Image` at all though.

For Rust we are looking at an elaborate ecosystem of different crates that support image manipulation. So on the one hand don't want to lock ourselves into depending on one crate only but make it as easy as possible to use SixtyFPS with as many image "source" crates (even software renderers) as possible. On the other hand we want to keep the list of public dependencies to a minimum to keep the API stable.

I suggest depending on [`imgref`](https://lib.rs/crates/imgref), not `image-rs` directly. That seems to fit our needs well and  appears to have a good history of releases, yet it's relatively easy to use also with `image-rs`. I like the approach femtovg has taken by defining an enum that wraps `ImgRef` and where the API takes an `Into`:

https://docs.rs/femtovg/0.2.2/femtovg/struct.Canvas.html#method.create_image

**Comment by ogoffart** [comment]
I've already drafted some code some time ago which i let commented out because i did not want to answer these questions:

https://github.com/sixtyfpsui/sixtyfps/blob/38cf156bf9a078ff969582d85291b4b05edad505/sixtyfps_runtime/corelib/graphics/image.rs#L57-L72

So that would be easy to implement. But ImageReference::EmbeddedRgbaImage is not implemented on all backend right now.


So imgref for rust seems like a right choice as it is stable for so long.

**Comment by ogoffart** [comment]
The adventage of using a SharedVector is that it does not re-allocates.
Maybe one can use imgref::Img<SharedVector>
