### ISSUE TITLE
Add support for window icon

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#39]
This ticket tracks the ability to set/get properties of window items that are rendered using the windowing system, such as the title or an icon image.

A list of possible properties:
  * title
  * icon
  * size constraints (maximum size, fixed size, etc.)

**Comment by ogoffart** [comment]
Title and size constraints are implemented. Remaining is the Icon

**Comment by ogoffart** [comment]
icon is done as well in 1360f1e26e38922639b1fef79ddf873fb890510f
