### ISSUE TITLE
Compilation error in qt_window.rs

### ISSUE THREAD

**Issue by cbeust** [sixtyfpsui/sixtyfps#399]
Building from HEAD, on Windows 10. `qmake` and `cl` are both on my path:

```
$ cargo run --bin gallery

...

Caused by:
  process didn't exit successfully: `C:\Users\cedri\rust\sixtyfps\target\debug\build\sixtyfps-rendering-backend-qt-7aee6c0e67db59d5\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=SIXTYFPS_NO_QT
  TARGET = Some("x86_64-pc-windows-msvc")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-pc-windows-msvc")
  CXX_x86_64-pc-windows-msvc = None
  CXX_x86_64_pc_windows_msvc = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-pc-windows-msvc = None
  CXXFLAGS_x86_64_pc_windows_msvc = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  DEBUG = Some("true")
  CXX_x86_64-pc-windows-msvc = None
  CXX_x86_64_pc_windows_msvc = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-pc-windows-msvc = None
  CXXFLAGS_x86_64_pc_windows_msvc = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CXX_x86_64-pc-windows-msvc = None
  CXX_x86_64_pc_windows_msvc = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-pc-windows-msvc = None
  CXXFLAGS_x86_64_pc_windows_msvc = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-I" "C:\\Users\\cedri\\rust\\sixtyfps\\sixtyfps_runtime\\rendering_backends\\qt" "-I" "D:/pd/qt2/6.1.2/mingw81_64/include" "-W4" "/std:c++17" "-FoC:\\Users\\cedri\\rust\\sixtyfps\\target\\debug\\build\\sixtyfps-rendering-backend-qt-a29ec05bf21b0b92\\out\\rust_cpp\\cpp_closures.o" "-c" "C:\\Users\\cedri\\rust\\sixtyfps\\target\\debug\\build\\sixtyfps-rendering-backend-qt-a29ec05bf21b0b92\\out\\rust_cpp\\cpp_closures.cpp"
  cpp_closures.cpp
  lib.rs(248): warning C4458: declaration of 'fnbox' hides class member
  lib.rs(232): note: see declaration of 'EventHolder::fnbox'
  qt_window.rs(1324): error C2664: 'QFont QFont::resolve(const QFont &) const': cannot convert argument 1 from 'QFont::ResolveProperties' to 'const QFont &'
  qt_window.rs(1324): note: Reason: cannot convert from 'QFont::ResolveProperties' to 'const QFont'
  qt_window.rs(1324): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
  D:\pd\qt2\6.1.2\mingw81_64\include\QtGui/qfont.h(275): note: see declaration of 'QFont::resolve'
  exit code: 2

  --- stderr


  error occurred: ToolExecError: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-I" "C:\\Users\\cedri\\rust\\sixtyfps\\sixtyfps_runtime\\rendering_backends\\qt" "-I" "D:/pd/qt2/6.1.2/mingw81_64/include" "-W4" "/std:c++17" "-FoC:\\Users\\cedri\\rust\\sixtyfps\\target\\debug\\build\\sixtyfps-rendering-backend-qt-a29ec05bf21b0b92\\out\\rust_cpp\\cpp_closures.o" "-c" "C:\\Users\\cedri\\rust\\sixtyfps\\target\\debug\\build\\sixtyfps-rendering-backend-qt-a29ec05bf21b0b92\\out\\rust_cpp\\cpp_closures.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).
```

**Comment by tronical** [comment]
Ah yes, that's an issue with an API change between Qt 5 and 6. I'll fix that.

**Comment by cbeust** [comment]
Now seeing

```
  = note: LINK : fatal error LNK1181: cannot open input file 'Qt6Cored.lib'
```

Happy to open a separate issue instead of piling on that one.

**Comment by tronical** [comment]
> Now seeing
> 
> ```
>   = note: LINK : fatal error LNK1181: cannot open input file 'Qt6Cored.lib'
> ```
> 
> Happy to open a separate issue instead of piling on that one.

I don't mind discussing this here, but let's see where it takes us :-)

That error messages suggests that MSVC is looking for the import library for Qt Core (the debug version). The earlier error message you posted had this bit in it:

```
"-I" "D:/pd/qt2/6.1.2/mingw81_64/include"
```

That's the include path to Qt, and presumably the same one that you're also using for linkage. From the name that appears to be a build of Qt that was done using MinGW. I believe the MinGW build of Qt will not create MSVC compatible import libraries, or differently put: It looks like the build is mixing MinGW artefacts with MSVC.

Since you have MSVC, I think it would be best to switch to the MSVC build of Qt as well.

**Comment by ogoffart** [comment]
That mingw issue was fixed in https://github.com/woboq/qmetaobject-rs/commit/3ebdca9a81463fb228e684f2fa59b87904a3d4c8
but that's not part of a release.
Maybe i should just publish a release of qttypes

**Comment by TillerBelotti** [comment]
I'm having this issue (note: LINK : fatal error LNK1181: cannot open input file 'Qt6Cored.lib') today. Does the aforementioned fix is included in any release?

**Comment by ogoffart** [comment]
Yes, the fix was released long ago.

**Comment by raphael-fritz** [comment]
> I'm having this issue (note: LINK : fatal error LNK1181: cannot open input file 'Qt6Cored.lib') today. Does the aforementioned fix is included in any release?

I ran into the same problem, adding` C:\Qt\6.5.1\msvc2019_64\lib` alongside `C:\Qt\6.5.1\msvc2019_64\bin` to path fixed it.
Although I later couldn't reproduce this because removing the lib from path again seems to have no effect as my build still compiles.

**Comment by emilfors** [comment]
I have this same issue, missing Qt6Cored.lib.
C:\Qt\6.4\mingw_64\bin and C:\Qt\6.4\mingw_64\lib on path.

**Comment by ogoffart** [comment]
@emilfors   This issue has been resolved, so it is likely some other problem.
Please create a **new** issue, including all the details such as the full error message
