### ISSUE TITLE
Add support for `font-size` to `LineEdit` in all styles

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#435]
### Discussed in https://github.com/sixtyfpsui/sixtyfps/discussions/434

<div type='discussions-op-text'>

<sup>Originally posted by **LouisGariepy** August 26, 2021</sup>
Hello! First of all, thanks for this wonderful project, I am falling in love with it :smile: .

I was wondering if there is a way to change the font size for this widget. Since there are width/height properties, it is natural to assume that there is a property to change the font size, but that doesn't seem to be the case.

Thanks!</div>

**Comment by besok** [comment]
I would love to implement this task.

**Comment by hunger** [comment]
@besok: Sure, go ahead!

We hang out in [mattermost](https://chat.sixtyfps.io/) if you have questions and need answers faster than github issues can provide them:-)

**Comment by besok** [comment]
Should it be done for the element TextEdit as well? 
I suppose so since they are very similar in general, does not it?

**Comment by hunger** [comment]
It would definitely make sense. So I would say: yes:-)
