### ISSUE TITLE
Text longer than LineEdit length isn't cut off and doesn't scroll

### ISSUE THREAD

**Issue by nyanpasu64** [sixtyfpsui/sixtyfps#457]
I'm testing `cargo install cargo-ui` (which defaults to the Qt theme) on Linux, with sixtyfps 0.1.1. When I type more text into a LineEdit than the size of the widget, the text past the end of the widget isn't cut off, and I can't scroll around in the text field by moving the cursor past the widget boundaries. This happens regardless of style.

![Screenshot_20210903_023946_Cargo UI](https://user-images.githubusercontent.com/913957/131985741-420240ed-00a5-47f6-927a-6a531489b44e.png)

**Comment by ogoffart** [comment]
Thanks for your testing and bug reports. 🤗

This issue was just fixed yesterday with https://github.com/sixtyfpsui/sixtyfps/commit/4f1eacd6d8d3584563aa97334956e44669115b76
