### ISSUE TITLE
Syntax Highlighting on Vim

### ISSUE THREAD

**Issue by samyak-jain** [sixtyfpsui/sixtyfps#508]
Does .60 have support for syntax highlighting for vim/nvim? I see we have support for kate and sublime and we seem to have lsp support for all the editors so I was wondering if there are any plans to add syntax highlighting support for vim?

**Comment by ogoffart** [comment]
See also https://github.com/sixtyfpsui/sixtyfps/issues/429

 And https://github.com/RustemB/sixtyfps-vim

I guess it's ok to close this issue as duplicated of #429 
We still need to add some documentation for it (Contributions welcome 😉)
