### ISSUE TITLE
Cursor blinks while Text Area is disabled

### ISSUE THREAD

**Issue by hunger** [sixtyfpsui/sixtyfps#513]
# Steps to Reproduce

* Go to the TextEdit tab of https://sixtyfps.io/releases/0.1.2/demos/gallery/
* click into one of the text areas. The cursor will be set and blinks there
* check "Disable Widgets" at the top

# Expected Result

The text cursor is disabled

# Actual result

The text cursor continues to blink

**Comment by tronical** [comment]
Yes. If a focused text input gets disabled, then it should not only stop the blinking cursor but the focus should also be cleared. And a disabled one should not accept the focus, of course.
