### ISSUE TITLE
error: failed to run custom build command for `servo-fontconfig-sys v5.1.0`

### ISSUE THREAD

**Issue by MahdiBehkar** [sixtyfpsui/sixtyfps#524]
error: failed to run custom build command for `servo-fontconfig-sys v5.1.0`

Caused by:
  process didn't exit successfully: `/home/mahdi/Rust/my-project/target/debug/build/servo-fontconfig-sys-136e4a39fa7e8154/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=FONTCONFIG_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=FONTCONFIG_STATIC
  cargo:rerun-if-env-changed=FONTCONFIG_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at '`"pkg-config" "--libs" "--cflags" "fontconfig" "fontconfig >= 2.11.1"` did not exit successfully: exit status: 1
  --- stderr
  Package fontconfig was not found in the pkg-config search path.
  Perhaps you should add the directory containing `fontconfig.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'fontconfig' found
  Package fontconfig was not found in the pkg-config search path.
  Perhaps you should add the directory containing `fontconfig.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'fontconfig' found
  ', /home/mahdi/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-5.1.0/build.rs:34:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by tronical** [comment]
Thank you for your report. What Linux district are you shinty? Do you have a dev package for fontconfig installed?

**Comment by MahdiBehkar** [comment]
> Thank you for your report. What Linux district are you shinty? Do you have a dev package for fontconfig installed?
Hi, yes, I have installed several packages before:
libfontconfig1-dev , 
libxcb-shape0-dev , libxcb-xfixes0-dev , libxkbcommon-dev

The packages are already installed on my system
My system:
ubuntu 20.04 x86_64 arch.

**Comment by tronical** [comment]
Good. What is the output you see in the terminal when you run pkg config manually?

`pkg-config --libs --cflags fontconfig`

**Comment by MahdiBehkar** [comment]
`% pkg-config --libs --cflags fontconfig`
error output:
**Package fontconfig was not found in the pkg-config search path.
Perhaps you should add the directory containing `fontconfig.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fontconfig' found**

**Comment by tronical** [comment]
Okay, that's at least symmetric to the error message. What about this one?

`pkg-config --list-all`

Do you have any environment variables related to png-config set, by chance? (`PKG_CONFIG_PATH` or `PKG_CONFIG_SYSROOT`)?

**Comment by MahdiBehkar** [comment]
No png configuration variables found, for example PKG_CONFIG_SYSROOT and PKG_CONFIG_PATH with the command pkg-config-list-all did not exist

**Comment by tronical** [comment]
> No png configuration variables found, for example PKG_CONFIG_SYSROOT and PKG_CONFIG_PATH with the command pkg-config-list-all did not exist

Sorry, there was perhaps a misunderstanding. The command is `pkg-config --list-all` (there's a space after `pkg-config`).

Alternatively, what does `dpkg -L libfontconfig-dev` show?

Somewhere there must be a `fontconfig.pc` file, and under my Ubuntu installation it's in the `libfontconfig-dev` package and located in `/usr/lib/x86_64-linux-gnu/pkgconfig/fontconfig.pc`.

**Comment by MahdiBehkar** [comment]
> Sorry, there was perhaps a misunderstanding. The command is `pkg-config --list-all` (there's a space after `pkg-config`).

I did not enter the command without a space, the command worked

Among the displayed variables, I could not find the two variables you mentioned

**Comment by MahdiBehkar** [comment]
± |main ?:8 ✗| → dpkg -L libfontconfig-dev
dpkg-query: package 'libfontconfig-dev' is not installed
Use dpkg --contents (= dpkg-deb --contents) to list archive files contents.

 mahdi-K54HR in ~/Rust/my-project
± |main ?:8 ✗| → sudo apt install libfontconfig-dev
[sudo] password for mahdi: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libfontconfig1-dev' instead of 'libfontconfig-dev'
libfontconfig1-dev is already the newest version (2.13.1-2ubuntu3).
The following package was automatically installed and is no longer required:
  libphobos2-ldc-shared-dev
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.

The package is installed but can not find

**Comment by MahdiBehkar** [comment]
`
Somewhere there must be a fontconfig.pc file, and under my Ubuntu installation it's in the libfontconfig-dev package and located in /usr/lib/x86_64-linux-gnu/pkgconfig/fontconfig.pc.`

There is also fontconfig.pc in the directory /usr/lib/x86_64-linux-gnu/pkgconfig/

**Comment by tronical** [comment]
> `
> 
> > Somewhere there must be a fontconfig.pc file, and under my Ubuntu installation it's in the libfontconfig-dev package and located in /usr/lib/x86_64-linux-gnu/pkgconfig/fontconfig.pc.
> 
> There is also fontconfig.pc in the directory /usr/lib/x86_64-linux-gnu/pkgconfig/

Okay, that's good!

Let's try this then:

`pkg-config --verbose --libs --cflags fontconfig`

This should among other things also tell us in which directories `pkg-config` looks.

Also, does `env | grep PKG_` show anything?

**Comment by MahdiBehkar** [comment]
Successfully compiled with command :
export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig

Thanks for taking the time to resolve the issue and thanks for sharing the fontconfig.pc path

**Comment by ogoffart** [comment]
Is there anything we should do so that other people don't run into this issue?

**Comment by LukeDSchenk** [comment]
> Thank you for your report. What Linux district are you using? Do you have a dev package for fontconfig installed?

Thanks for this @tronical, solved an issue for me using a completely different library!

**Comment by omarandlorraine** [comment]
>Thanks for this @tronical, solved an issue for me using a completely different library!

Me too, I'm using ggez which also pulls in servo-fontconfig-sys. Maybe we ought to open an issue with servo-fontconfig-sys to put in a more helpful error message or something

**Comment by Samu01Tech** [comment]
Had the same problem but on Fedora. Run `sudo dnf install fontconfig-devel` and the file `fontconfig.pc` should be in `/usr/lib64/pkgconfig` and that is the path to export.

**Comment by duxpe** [comment]
> Successfully compiled with command : export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
> 
> @tronical Thanks for taking the time to resolve the issue and thanks for sharing the fontconfig.pc path

Had the same problem when building from a ubuntu 22.04.4 fresh install, thank you guys for the help!
I think that @ogoffart might have a point... don't know if there is something to be done so we could prevent this behaivor to happen again.

**Comment by tronical** [comment]
Oh? We don’t use pkg-config anymore to locate font config as build time - or at least we shouldn’t :). Could you paste the build error you ran into?
