### ISSUE TITLE
different behaviour in debug and release mode

### ISSUE THREAD

**Issue by burrbull** [sixtyfpsui/sixtyfps#526]
I have installed Qt.
When I do `cargo run` program uses Qt backend.
When I do `cargo run --release` it uses own backend.

**Comment by ogoffart** [comment]
What platform and compiler are you using?
Is there any log when compiling that might indicate a reason why this wouldn't work? 

My suspission is that on window/msvc, the libraries have different names for release and debug, and maybe only the debug ones are installed or found?

**Comment by burrbull** [comment]
Ubuntu 20.04 with Qt 5.15 from ppa.
So maybe it is only my problem.

**Comment by ogoffart** [comment]
I am puzzled and I see no reasons why the backend should be different in release and in debug mode.

Do you see this message when compiling in release? 
```
warning: Could not find a Qt installation. The Qt backend will not be functional.
```
Maybe you can add some debug in the `build.rs` of the `qttypes` crate to find out why it does not find Qt in release.

**Comment by burrbull** [comment]
After `cargo clean` it runs Qt on both. So it is my fault.
