### ISSUE TITLE
Add support for css named colors in the compiler

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#53]
Allow for the convenient use of the common color names in `.60` markup.

We could use https://crates.io/crates/css-color-parser2

The documentation of the language reference should also mention what syntax is possible.

You can use plain names if it's evident to the compiler that the property type is a color. If that's not clear, then a `Color.` prefix is required. The hashed variant is always a color. This permits the following two variants:

```
Rectangle {
    color: rgba(00, ff, 00, ff);
}
```

or

```
Rectangle {
    signal hsl;
    color: Color.hsl(12, 34, 56);
}
```

**Comment by ogoffart** [comment]
We support all the CSS color, but only within color properties.
`Color.foo` is not yet implemented.  Nor are the hsl or rgb functions.
