### ISSUE TITLE
Fullscreen rendering with Wayland/Weston aborts when minimum size exceeds the screen display

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#532]
When showing a window on a screen managed by Weston the Wayland compositor and setting `SIXTYFPS_FULLSCREEN=1` *and* either the minimum width or height of the Window exceeds the corresponding dimension of the screen, the application aborts with an error message (dimensions changed of course):

```
xdg_wm_base@15: error 4: xdg_surface buffer (772 x 504) is larger than the configured fullscreen state (800 x 425)
```

It could be that we are applying constraints somewhere and trying to make the window surface bigger than the size that we received. It might also be something that's happening inside winit or glutin.

A workaround is to not set `SIXTYFPS_FULLSCREEN=1` and instead run Weston with the kiosk shell (for example `--shell=kiosk-shell.so`), as that supports clipping the window.

**Comment by ogoffart** [comment]
We do apply the constraints for minimum and maximum.
Does that mean that when setting full screen, we should not set the contraints, as a workaround?

**Comment by tronical** [comment]
Yes, not setting the inner size in apply_window_properties might do the trick. I’ll try.
