### ISSUE TITLE
Allow distinguishing mouse buttons

### ISSUE THREAD

**Issue by phi-gamma** [sixtyfpsui/sixtyfps#535]
Currently the ``clicked`` callback of ``TouchArea`` fires for every button on
my mouse but there is no way to tell them apart. It would be nice to receive
an equivalent of  ``QMouseEvent`` instead with more information about what
button was actually clicked.

**Comment by ogoffart** [comment]
That's right, we need to improve on that.

Here is the API we are now considering:
```rust
enum PointerEventButton  { none, left, right, middle }
enum PointerEventKind { up, down, cancel }


struct PointerEvent := {
    kind: PointerEventKind,
    button: PointerEventButton,

    //pointer-id: int,     // in the future when we support multi-touch
}

TouchArea := _ {
   // added already in master.  The position can be accessed with the mouse-x, mouse-y  properties
   callback moved();
   // replaces the "pressed-changed" in master
   callback pointer-event(PointerEvent);
}
```

I hope this will fit your use-case.

**Comment by phi-gamma** [comment]
Whoa, you guys are lightning fast. Thanks!

One question:

    +            MouseEvent::MousePressed { pos, button } => {
    +                if button == PointerEventButton::left {
    +                    Self::FIELD_OFFSETS.pressed_x.apply_pin(self).set(pos.x);
    +                    Self::FIELD_OFFSETS.pressed_y.apply_pin(self).set(pos.y);
    +                    Self::FIELD_OFFSETS.pressed.apply_pin(self).set(true);
    +                }
    +                Self::FIELD_OFFSETS

Could you elaborate on the motivation behind that restriction? This has a weird
effect on mouse drag for the right and other buttons in that ``pressed-{x,y}``
always contains the coordinates of the last LMB event (or 0,0 initially).

**Comment by ogoffart** [comment]
> Could you elaborate on the motivation behind that restriction? 

You mean that `pressed` is only true when the left button is pressed and not other buttons?

I kind of thought that the `pressed`would be more usefull to mean the main (left) button is pressed, as I expect that most widgets will most likely want to interact only with the left button.
Am I wrong in there? Do you think that the `pressed` and `pressed-x`,`-y` should be meaning that any button is pressed?
Maybe we want something like `left-pressed`, `middle-pressed`, `left-pressed-pos` and so on?

----

Note that you could maintain these properties yourself with something like
```
property <Point> right-pressed-point;
property <bool> right-pressed;
pointer-event(event) => {
  if (event.kind == PointerEventKind.cancel) { 
     right-pressed = false;
  } else if (event.button == PointerEventButton.right) {
    right-pressed = event.kind == PointerEventKind.down;
    right-pressed-point = { x: mouse-x; y: mouse-y; }
  }
}
```

**Comment by phi-gamma** [comment]
> > Could you elaborate on the motivation behind that restriction? 
> 
> You mean that `pressed` is only true when the left button is pressed and not other buttons?

Yeah.

> I kind of thought that the `pressed`would be more usefull to mean the main (left) button is pressed, as I expect that most widgets will most likely want to interact only with the left button.
> Am I wrong in there? Do you think that the `pressed` and `pressed-x`,`-y` should be meaning that any button is pressed?
> Maybe we want something like `left-pressed`, `middle-pressed`, `left-pressed-pos` and so on?

Not disagreeing with you, that is entirely reasonable. I was just
a bit puzzled when testing the new code. So far it sufficed to
compare the “pressed” coordinates to the event coordinates to
detect drag vs. click and that approach doesn’t work for the
other buttons. I don’t actually *need* it to work, just curious.

> ----
> 
> Note that you could maintain these properties yourself with something like
> ```
> property <Point> right-pressed-point;
> property <bool> right-pressed;
> pointer-event(event) => {
>   if (event.kind == PointerEventKind.cancel) { 
>      right-pressed = false;
>   } else if (event.button == PointerEventButton.right) {
>     right-pressed = event.kind == PointerEventKind.down;
>     right-pressed-point = { x: mouse-x; y: mouse-y; }

Thanks for the suggestion!
