### ISSUE TITLE
Keyboard focus 

### ISSUE THREAD

**Issue by ogoffart** [sixtyfpsui/sixtyfps#55]
For accessibility reasons, the UI need to be usable with the keyboard.
So we need a keyboard focus. (also for text input)

Element that can gain the focus should be known to the compiler, and would have a `has_focus` property which specify if the element currently has the focus.  

* Do we need a difference between `active_focus` and `focus` ?  (i.e: is it possible that a element has the focus property set to true while not in fact, having the current focus because, say, another component is active in another "tab" or "window")

We would also need a way to tell where the focus should go by pressing tab. By default, one would compute the most reasonable chain geometrically.  but this should be possible to override in the .60 using tab index property, or some kind of chaining

**Comment by tronical** [comment]
I think we need something like `active_focus` the moment we introduce focus scopes. For consistency with `has_focus` I suggest to call the property `wants_focus`.

**Comment by ogoffart** [comment]
> I think we need something like active_focus the moment we introduce focus scopes. For consistency with has_focus I suggest to call the property wants_focus.

What's the use case for having these different properties. It must not be confusing and the semantic must be clear.

The use case i have in mind for focus property looks like this:

```60
Foo {
     // 1. Binding on focus to control the appearence if the object is focussed
     color: focus ? red: blue;

     on_something {
            // 2. manually sets the focus to an item, eg, when entering a page or something.
           some_item.focus = true;
     }

    // 3. When this window/tab/sub-region aquire the focus, 
    // this is the particular widget which aquire the focus
    focus: true;

    // The focus is set based on a condition: does that make sense?
    focus: some_settings.sholuld_have_focus;
}
```

I think it only make sense to show the active focus. Or is there use case where we are interested on a different kind of focus in binding expression?

As for setting the focus,  in my experience, one almost always want to set the active focus.

For the last use-case of setting the focus with `focus:`, this is indeed a more local focus which is not the active focus. I guess we can make the compiler understand that when setting the focus in a .60 file is the default default focus on a region.

**Comment by tronical** [comment]
I agree about those 3 use-cases (reading focus property, programmatically setting focus and expressing desire to receive focus when window/tab/sub-region acquires).

I think (1) and (2) are well covered with a single property, ideally called `focus` indeed. That is simple and readable.

It's (3) that kind of ruins it :-) and I think it goes hand-in-hand with the question: How do you define these sub-regions? If, for example, we address (3) rather by means of declaring a "forwarding", then perhaps we can just stay with one "focus" property. I'd like that.

**Comment by tronical** [comment]
A styled `LineEdit` could perhaps serve as example:

```
LineEdit := Rectangle {
    border_color: root.has_focus ? #556884 : #ffffff;
    forward_focus: input;
    // ...
    GridLayout {
        padding: 3lx;
        input := TextInput {
           ...
        }
    }
}
```

Let's say we allow defining a `forward_focus` property. That could perhaps also create a `focus` alias to the forwarded element (`property <bool> focus; focus <=> input.focus` in the above example`).

**Comment by tronical** [comment]
The basic focus handling is implemented now, with ```TextInput``` as the only element supporting keyboard events right now. ```has_focus``` is the visible property for reading, ```someitem.focus()``` can be called to explicitly focus an element and ```initial_focus: some_item;``` can be used to point to an item that either shall receive the initial focus or by itself forwards using another ```initial_focus``` binding.
