### ISSUE TITLE
`PointerEventKind` always passed as `down` variant

### ISSUE THREAD

**Issue by Bendrien** [sixtyfpsui/sixtyfps#558]
I just tried the new `pointer-event` callback on the `TouchArea` and was not able to distinguish between the event kinds. It seems like it is always set to `PointerEventKind.down`.

```
// This is embedded in some layout so that the `has-hover` property can change
TouchArea {
    pointer-event(e) => {
        if (e.button == PointerEventButton.left) {
            background = #F00;
        } else if (e.button == PointerEventButton.middle) {
            background = #0F0;
        } else if (e.button == PointerEventButton.right) {
            background = #00F;
        } else if (e.button == PointerEventButton.none) {
            // This line is reached sometimes without any press involved?
            // Also different behavior regarding the left button vs the rest
            background = #000;
        }
        
        if (e.kind != PointerEventKind.down) {
            // This line is never reached :(
            background = #FFF;
        }
    }
}
```

Some additional things I noticed about the new callback:
* I was not able to use color names like `blue` or `red` within the callback.
* The `pointer-event` callback gets called with a `PointerEventButton.none` even though no button press was involved (when just leaving the `TouchArea`). Is this per design?
* There is different behavior when clicking in the `TouchArea`, leaving it and releasing the button:
    * With all buttons but the left an intermediate `pointer-event` with `PointerEventButton.none` gets triggered.
    * With the left button __no__ intermediate `pointer-event` happens.
* What is the purpose of the `clicked` callback now? Would it be possible to replace its functionality with `pointer-event` callback?

**Comment by ogoffart** [comment]
Thanks for reporting the issue
This is a bit embarrassing.
(That's what happens when implementing a feature too close to a release without properly testing it,
But we wanted to get that done because we had implemented another way in master that was not flexible enough and did not want to release with that)

Anyway: the problem is fixed now.
