### ISSUE TITLE
ListView inside of VerticalLayout causes crash

### ISSUE THREAD

**Issue by jamesblacklock** [sixtyfpsui/sixtyfps#595]
The following component causes a crash when using the Qt backend on macOS:
```
import { ListView } from "sixtyfps_widgets.60";

export Test := Window {
    VerticalLayout {
        ListView {}
    }
}
```

Error message: `QPainter::begin: Paint device returned engine == 0, type: 3`

**Comment by tronical** [comment]
I can reproduce this
