### ISSUE TITLE
Clean up Rust `Model` trait for 0.2.0

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#600]
After PR #599 changed the `Model` trait, it'll be time to clean it up for the next breaking release:

 * `fn model_tracker(&self) -> &dyn ModelTracker` should not have a default implementation
 * `fn attach_peer(&self, peer: ModelPeer)` should be removed
 * `ModelNotify::attach` should be removed

**Comment by ogoffart** [comment]
> perhaps model_tracker should retain its empty implementation to make it easier to write read-only models?

You mean constant model.

If it is mendatory to implement it, it makes the developer think twice if it should return something or not. Otherwise it may be easy to forget.

**Comment by hunger** [comment]
Todo items:

- [ ] `Model::row_data(...)` should return `Option<T>`, not a plain `T`
- [ ] fn model_tracker(&self) -> &dyn ModelTracker should not have a default implementation
- [ ] fn attach_peer(&self, peer: ModelPeer) should be removed
- [ ] ModelNotify::attach should be removed
