### ISSUE TITLE
"fluent" Slider widget doesn't call changed(value) callback when slider moved

### ISSUE THREAD

**Issue by alexd3rsan** [sixtyfpsui/sixtyfps#621]
As stated in the title, if one uses a fluent ``Slider`` widget from ``sixtyfps_widgets.60`` (in my case in version 1.1.4 on rust), it doesn't call the ``changed(value)`` callback when the ``TouchArea``'s ``moved()`` callback is called.

To reproduce the issue, one can run this [code snippet](https://sixtyfps.io/releases/0.1.4/editor/?snippet=%0Aimport+%7B+Slider+%7D+from+%22sixtyfps_widgets.60%22%3B%0A%0ADemo+%3A%3D+Window+%7B%0A+++Slider+%7B%0A++++height%3A+50px%3B%0A%0A++++changed%28value%29+%3D%3E+%7B%0A++++++++debug%28value%29%3B%0A+++%7D%0A+++%7D%0A%7D%0A) in a local project, move the slider around and anticipate no debug output getting printed.

In my case it worked as expected after adding a call to ``changed(value)`` below line 231 ([permalink](https://github.com/sixtyfpsui/sixtyfps/blob/ae25dd3d079bd775071568a96fce38a0da8905f5/sixtyfps_compiler/widgets/fluent/sixtyfps_widgets.60#L231)) of the ``sixtyfps/sixtyfps_compiler/widgets/fluent/sixtyfps_widgets.60`` file, so that the full definition of the ``moved()`` callback now reads:

```
moved => {
            if (enabled && pressed) {
                value = max(root.minimum, min(root.maximum,
                    pressed-value + (touch.mouse-x - touch.pressed-x) * (maximum - minimum) / (root.width - handle.width)));
                changed(value);
            }
        }
```

I'm not sure if this "fix" would break anything else or if I'm missing something as to why it would be working as intended like this, but this behavior caused some confusion for me whilst implementing my first real application using the fluent backend.

I've had a good experience using this version with rust on Windows otherwise so far! 😄

**Comment by ogoffart** [comment]
Thanks for the bug report!
Your analysis is entirely correct.
