### ISSUE TITLE
Goal of the project

### ISSUE THREAD

**Issue by nagayev** [sixtyfpsui/sixtyfps#652]
Hello. I read SixtyFPS `Fit into a few hundred kilobytes of RAM`.
So I ran gallery example and saw 24.7 MB of RAM usage and 81 MB of shared memory.
What is the profit?

**Comment by tronical** [comment]
We are aiming to fit into a few hundred kilobytes of RAM. I'm not sure how likely that is going to be on typical desktop platforms, where for example the high resolution on a screen itself will require megabytes of RAM for image buffers, but we are aiming to fit into the few hundred kilobytes of RAM of a microcontroller. This is work that has begun.

**Comment by nagayev** [comment]
@tronical Okey, thank you
