### ISSUE TITLE
image-url doesn't use the relative path of the folder containing cargo.toml on macOS

### ISSUE THREAD

**Issue by jrmoulton** [sixtyfpsui/sixtyfps#665]
I'm following along with the memory game example but the paths for the images in the icons folder are not found. When I add in the full system path though then the images are found.

**Comment by tronical** [comment]
The path in @image-url() is resolved relative to the path of the `.60` file it is used in, not `Cargo.toml`.

Relative to Cargo.toml, where are the images located for you?

Maybe we need to clarify something in the tutorial docs :-)

**Comment by jrmoulton** [comment]
Ahh good to know. That fixed it.

Yeah on this page of the tutorial the documentation is confusing. 
https://sixtyfps.io/releases/0.1.3/docs/tutorial/rust/memory_tile.html
> Inside the Rectangle we place an Image element that loads an icon with the @image-url() macro. The path is relative to the folder in which the Cargo.toml is located.

Thanks!
