### ISSUE TITLE
Setting focus to a `FocusScope` on startup

### ISSUE THREAD

**Issue by Kirottu** [sixtyfpsui/sixtyfps#666]
There doesn't seem to be any way that I could find to run any code when the window gets created. Right now clicking on the widget to activate the focus counters the entire point of having a keybind for this sort of action (activating something that would need to be pressed otherwise) in the first place.

**Comment by tronical** [comment]
On focusable elements like `TextInput` as well as on `FocusScope` you can call `focus()` to activate the focus. There's an example in https://github.com/sixtyfpsui/sixtyfps/blob/master/docs/langref.md#focus-handling . There's also the `forward-focus` property that allows delegating, which is also available on the `Window`. If you set it there then that's the element that'll be focused when the window is first shown.

**Comment by Kirottu** [comment]
Alright thank you! That works like a charm.
