### ISSUE TITLE
Add support for property aliases

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#67]
Sometimes we have components that wrap others, such as `LineEdit` maybe using a `TextInput` internally. In that case we want to expose the `TextEdit`'s `text` property in `LineEdit`, so that setting it forwards and reading it will fetch from the internal `TextInput`.

The ability to alias properties would help accomplish that.

Acceptance criteria: Aliases implemented, tested and documented.

**Comment by ogoffart** [comment]
Maybe what we want is not property aliases, but two ways binding.

For example , it could look like:

```
   LineEdit {
      text <=> settings.first_name;
   }
```

**Comment by tronical** [comment]
You're right, two-way bindings address the specific issue I'm facing as well as a few others. Just thinking out loud:

1. If two properties are supposed to be bound together, perhaps the property handle of one property could point to the bound property. Any get() will fetch from the other property, any set() and set_binding() will forward. Not sure yet though how to indicate that, since we use both free bits (lock and binding bit). Perhaps one more binding allocation.

2. If the compiler sees a two-way binding between two properties where at least one is declared in `.60` itself, then it could eliminate one in favour of the other and adjust PropertyReferences. There are probably a few combinations how the compiler could treat this in terms of optimisations.

**Comment by ogoffart** [comment]
both could work i think.  We would need to have the property handle refcounted, but that's doable.
