### ISSUE TITLE
failed to write request: The pipe is being closed. (os error 232)

### ISSUE THREAD

**Issue by sciguyryan** [sixtyfpsui/sixtyfps#674]
Hi.

I have run into an odd error when using `sixtyfps::include_modules!()`. Every time I include it I get the following error: "failed to write request: The pipe is being closed. (os error 232)".

It might be related to rust-analyzer since the code actually compiles and runs perfectly well. I am reporting it here to get some feedback, before reporting it to them.

I have followed the beginners guide, and since it actually compiles and runs I don't think it is anything I have done incorrectly.

Any advice or feedback would be welcome.

Cheers!

**Comment by tronical** [comment]
Hmm, I don't think I've seen this before (but I haven't seen much :). Just to double check: This is happening in a project where you're using `sixtyfps_build::compile(...)` in your `build.rs` and `sixtyfps::include_modules!()` in your `main.rs` (or something like that), and the project runs just fine but rust-analyzer produces these errors?

Are you using rust-analyzer through visual studio code? Which version of rust-analyzer are you using?

**Comment by sciguyryan** [comment]
>This is happening in a project where you're using sixtyfps_build::compile(...) in your build.rs and sixtyfps::include_modules!() in your main.rs (or something like that), and the project runs just fine but rust-analyzer produces these errors?

This is correct.

> Are you using rust-analyzer through visual studio code? Which version of rust-analyzer are you using?

That is also correct. I am currently using the latest version, which is the one dated 2021-11-22.

**Comment by ogoffart** [comment]
I did seen this error message recently.
Also seen it on other macros

![Screenshot_20211124_101022](https://user-images.githubusercontent.com/959326/143208387-9ae693ec-d600-4e9a-9618-e86331227ebb.png)

Looks like a rust-analyzer bug to me.

**Comment by ogoffart** [comment]
looks like https://github.com/rust-analyzer/rust-analyzer/issues/10766

**Comment by ogoffart** [comment]
I'm going to close this issue as this is a rust-analyzer bug.  Thanks for reporting anyway!

**Comment by alexjg** [comment]
Just noting that this is not the rust-analyzer bug you've posted - although I can understand why you might think that it is as the error message is the same. The issue you've linked has been fixed for the code and rustc and rust-analyzer versions posted, you'll need to open a new issue with the rustc and rust-analyzer versions you're using, as well as the code which causes the issue.
