### ISSUE TITLE
Issue with switching away from dark mode on MacOS native interface

### ISSUE THREAD

**Issue by cmot17** [sixtyfpsui/sixtyfps#687]
When switching away from dark mode, things generally seem to break. 

This is on MacOS 12.0.1.

https://user-images.githubusercontent.com/25753364/143527325-1be202ac-b2a8-4b02-9f4c-3fea91342520.mov

**Comment by ogoffart** [comment]
in the Qt backend, we would need to listen to the QEvent::StyleChanged, i guess, and update the StyleMetrics properties that sets the color
