### ISSUE TITLE
Add version macros to the C++ API

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#705]
In order to make it easier for a C++ application to support different versions of potentially slightly incompatible APIs, it would be useful to identify the current version via pre-processor macros.

I suggest we add

```cpp
#define SIXTYFPS_VERSION_MAJOR XX
#define SIXTYFPS_VERSION_MINOR YY
#define SIXTYFPS_VERSION_PATCH ZZ
#define SIXTYFPS_VERSION ((SIXTYFPS_VERSION_MAJOR << 16) | (SIXTYFPS_VERSION_MINOR << 8) | SIXTYFPS_VERSION_PATCH)
```

to `sixtyfps.h`.

**Comment by ogoffart** [comment]
Currently there is `sixtyfps::private_api::VersionCheck` enum, but as the name show it is private API.
Having a `SIXTYFPS_VERSION` macro make sense. I don't know about the _MAJOR, _MINOR, _PATCH ones.
What's the accepted practice for C++ library?

**Comment by tronical** [comment]
I'm sure there's anecdotal evidence of libraries just providing only one pre-processor macro, but I believe in a majority that provides also the individual versions as pre-processor macros. I've also seen FOO_VERSION_STRING to save users one step of stringifying.

This ties also a bit into the meaning of the version and readability of the code that uses it. Since we're using semantic versioning, I think `#if SIXTYFPS_VERSION_MAJOR <= 0x1` is easier to read and less error prone to write than `#if SIXTYFPS_VERSION <= 0x010000`.

I don't see a downside :-)

**Comment by ogoffart** [comment]
did a small survey:

Boost only has one macro and uses base 100: https://www.boost.org/doc/libs/1_76_0/boost/version.hpp
Qt using the schema you describe (obviously :-) )
gtkmm: use 3 define and a check: https://developer-old.gnome.org/gtkmm/stable/group__Version.html
different standard library uses different format. usually VVRR or 0xVVRR : https://sourceforge.net/p/predef/wiki/Libraries/

**Comment by tronical** [comment]
What could be an argument for not providing individual version macros?

Maintenance on our side when changing it?

**Comment by ogoffart** [comment]
Ok, let's just provide them, they can be auto_generated by the cbindgen.rs script.
Should they replace the sixtyfps::private_api::VersionCheck enum completely?
