### ISSUE TITLE
Global CMake build that builds everything

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#71]
It would be great to have a top-level CMake build that builds the run-time library, the compiler, etc. everything needed in one go. That would make it much easier for C++ developers to use.

**Comment by ogoffart** [comment]
Mostly done.
What remains to do is:
 * [ ] Not build and re-build all the crates (blocked on https://github.com/AndrewGaspar/corrosion/issues/57 )
 * [ ] Fix `make install'
