### ISSUE TITLE
Unknown property border-width in ListView Error on macOS

### ISSUE THREAD

**Issue by jrmoulton** [sixtyfpsui/sixtyfps#710]
I get the above error when compiling my .60 file on macOS but it compiles just fine on linux. 
```    
  document := Rectangle {  
        list_view := ListView {
            border-width: 10px;
            y: 10px;
            x: 10pt;
            for text_element[i] in TextElements : Text {
```
Should this property exist or not exist?

**Comment by ogoffart** [comment]
Well, this is actually a problem that internal properties are re-exposed. The thing is that it depends on the style, and on the fluent style, ListView "inherit" Rectangle, but not on the native style.
So one should not rely on the existence of such properties.
In a future release, we plan to make it better. See discussion in https://github.com/sixtyfpsui/sixtyfps/issues/191

**Comment by jrmoulton** [comment]
Ahhh I see. Thanks for the link. 
The reason I was using it was that I was creating a ListView inside of an outer Rectangle and when I did that a small black border appeared. I was able to disable it by setting border-width to 0 but if I shouldn't count on that existing how should I disable that border?

**Comment by jrmoulton** [comment]
Being able to disable the border would be great but in my particular use case the border was appearing because I was setting the x and y values of the view. Instead I left the x and y of the view alone and changed the x and y of the elements inside of the view and the border is no longer visible.
