### ISSUE TITLE
Dropdown text not visible on dark themes

### ISSUE THREAD

**Issue by TabulateJarl8** [sixtyfpsui/sixtyfps#720]
Hi. I was testing out the sixtyfps gallery example, and I noticed something strange. The text in the dropdown is white, and the dropdown background is also white, causing the text to be unreadable. I don't know if it matters, but I'm using the Rust version, and this happens on both my desktop and laptop. I'll attach a screenshot to the issue.

![image](https://user-images.githubusercontent.com/58576759/144874966-89d9c5f0-a176-48fa-a7a9-b9b7e6e9d946.png)

**Comment by ogoffart** [comment]
Thanks for the bug report!
Should be fixed now.
