### ISSUE TITLE
Reusing a property results in a panic 'already mutable borrowed: Borrow Error'

### ISSUE THREAD

**Issue by jrmoulton** [sixtyfpsui/sixtyfps#737]
I keep finding myself wanting use a property as a variable inside of a widget but re-using any property that I create more than once time will result in a borrow error. This code for example won't compile because num_elements is used more than once. Is this something that I am doing wrong/ is there a better way?
```    
Rectangle {
        property <int> num_elements;
        num-elements: 3;
        Key { pos: 1; num_elements: num_elements; }
        Key { pos: 2; num_elements: num_elements; }
        Key { pos: 3; num_elements: num_elements; }
    }
```

**Comment by ogoffart** [comment]
Thanks for the bug report.

num_elements refer the the property in key.
The correct way to express this would be `num_elements: parent.num_elements;`

But anyway, the panic is clearly a bug and a decent error message is in order.
