### ISSUE TITLE
exponent and logarithm math functions

### ISSUE THREAD

**Issue by Be-ing** [sixtyfpsui/sixtyfps#755]
It would be useful to use exponential and logarithm functions on numeric values in `.60` files.

**Comment by jrmoulton** [comment]
I'm currently working on this issue. In rust, on an f64, there are functions for `log2`, `log10` and `log`. The regular log in rust takes an argument of an arbitrary base but from as far as I can tell the sixtyfps math functions don't support arguments. Would it just be best to add support for `log2`, `log10`, and `ln`?

**Comment by jrmoulton** [comment]
Nevermind. The sixtyfps math functions do support multiple arguments. Because of this the bare minimum is to support `log` with an arbitrary base but would it be practical in this case to also support log2 and log10 just like in rust and c++?
