### ISSUE TITLE
Panic with `Recursion Detected` when using a VerticalLayout inside of a Scrollview

### ISSUE THREAD

**Issue by jrmoulton** [sixtyfpsui/sixtyfps#772]
I'm trying to use a VerticalLayout inside of a scroll view but the code panics. 

The problematic code is
```
SideBar := Rectangle {
	width: 185px;

	ScrollView {
		VerticalLayout {
			SearchBox {
				width: parent.width - 20px;
			}
			ListenSection {  }
		}
	}
}
```
Is there a better way to do this?

**Comment by ogoffart** [comment]
This is caused by a binding loop, which is not detected by the compiler for some reason (bug in the compiler probably). I would need to have a reproducable example to debug it.

**Comment by jrmoulton** [comment]
```
SideBar := Rectangle {
    width: 185px;

    ScrollView {
        VerticalLayout {
            Rectangle {
                width: parent.width - 20px;
            }
        }
    }
}
```
Ahh ok the problem is coming from the `width: parent.width` - 20px; line. If that line isn't there everything works fine but if it is there then it crashes with a panic

**Comment by jrmoulton** [comment]
And with a little more testing it only happens when the `VerticalLayout` is inside the `ScrollView`. If the `ScrollView` is inside the `VerticalLayout` it compiles. And if only one of the two is present that will also compile.

**Comment by ogoffart** [comment]
I have debugged the reason why we don't detect a loop.
It turns out this can be reproduced in this testcase:

```
Alias := Rectangle {
    property <int> viewport_width ;
    property <int> ps_width <=> viewport_width;
}

Foo := Rectangle {
    property <int> layout_info: alias.viewport_width;

    alias := Alias {   ps_width: layout_info;   }

    Text {
        text: layout_info;
    }
}
```

**Comment by ogoffart** [comment]
Now this is properly detected as a compile time error (binding loop)
