### ISSUE TITLE
proposal: alternative syntax for initializing an array in .60 files

### ISSUE THREAD

**Issue by Vollbrecht** [sixtyfpsui/sixtyfps#774]
## alternative syntax proposal
in rust one can write something like the following to init an array
` let ys: [i32; 500] = [20; 500]; ` 

to fit inline with current styling in the .60 files maybe something like this can exist:
` property <[int]> ys: [20;500];` to declare and instantiate a longer array easily. 

this should create an array with 500 elements of int all with the value 20.

## usecase 
reduce clutter in following example code:
``` 
export struct my_curve := {
    line: bool,
    arc:bool,
    cubic: bool,
    quadratic: bool,
    from_x: float,
    from_y: float,
    to_x: float,
    to_y: float,
    control-1-x: float,
    control-1-y: float,
    control-2-x: float,
    control-2-y: float,
    large-arc: bool,
    sweep: bool,
    visible: bool,
}

property<[my_curve]> array_of_paths : [{    line: false,
                                            arc: false,
                                            cubic: true,
                                            quadratic: false,
                                            from_x: 0,
                                            from_y: 0,
                                            to_x: 320,
                                            to_y: 240,
                                            control-1-x: 160,
                                            control-1-y: 240,
                                            control-2-x: 0,
                                            control-2-y: 0,
                                            large-arc: false,
                                            sweep: false,
                                            visible: false,
                                        },
                                        {    line: false,
                                            arc: false,
                                            cubic: true,
                                            quadratic: false,
                                            from_x: 0,
                                            from_y: 0,
                                            to_x: 320,
                                            to_y: 240,
                                            control-1-x: 160,
                                            control-1-y: 240,
                                            control-2-x: 0,
                                            control-2-y: 0,
                                            large-arc: false,
                                            sweep: false,
                                            visible: false,
                                        },
                                        {    line: false,
                                            arc: false,
                                            cubic: true,
                                            quadratic: false,
                                            from_x: 0,
                                            from_y: 0,
                                            to_x: 320,
                                            to_y: 240,
                                            control-1-x: 160,
                                            control-1-y: 240,
                                            control-2-x: 0,
                                            control-2-y: 0,
                                            large-arc: false,
                                            sweep: false,
                                            visible: false,
                                        },
                                        {    line: false,
                                            arc: false,
                                            cubic: true,
                                            quadratic: false,
                                            from_x: 0,
                                            from_y: 0,
                                            to_x: 320,
                                            to_y: 240,
                                            control-1-x: 160,
                                            control-1-y: 240,
                                            control-2-x: 0,
                                            control-2-y: 0,
                                            large-arc: false,
                                            sweep: false,
                                            visible: false,
                                        },];

``` 
this gets worse fast for long arrays. with the proposed syntax it could be much shorter.

 is this a valid use case or should we focus on creating always only a minimum of structs in an array. Creating more dynamically later in the application code?

**Comment by ogoffart** [comment]
I just wonder if this happen so often that one need to create such array of identical items from the .60 code.
Probably one wants to create that in the native code.
But if we want, a `[value ; count]` syntax doesn't look too bad.

**Comment by Vollbrecht** [comment]
I see your point here, and i am starting to feel the same working longer with sixtyfps. The idea came from my learning curve with sixtyfps. Sixtyfps documentation referees to  property <[type]> as an array of type. Idiomatic i thought of this as an rust array which has an fixed size at compile time which cannot be changed in size. So i thought i needed to create a large enough array at compile time. Alter get my toe wet manipulating the array property in the equivalent rust code, and learned that i don't even have to init the array in .60 at all. 
So i would recommend extend the documentation on this point. I use this project because i think it has a far better documentation that any other equivalent project i looked at. I think https://docs.rs/sixtyfps/latest/sixtyfps/docs/generated_code/index.html is underutilized here. Maybe there should be an example here how to interface with such an property array in rust and than link it back to the langref.md. Than i think i wouldn't have come up with this. Thank you!

**Comment by tronical** [comment]
> So i would recommend extend the documentation on this point. I use this project because i think it has a far better documentation that any other equivalent project i looked at. I think https://docs.rs/sixtyfps/latest/sixtyfps/docs/generated_code/index.html is underutilized here. Maybe there should be an example here how to interface with such an property array in rust and than link it back to the langref.md. Than i think i wouldn't have come up with this. Thank you!

Good idea! Please feel free to file a ticket for this (or I can also file it, just let me know).
