### ISSUE TITLE
Support loading image with `img!"https://some-url"`  of the wasm build

### ISSUE THREAD

**Issue by ogoffart** [sixtyfpsui/sixtyfps#82]

**Comment by tronical** [comment]
Commits 6c9f0691aa067111c9f77d2fe7e85f9e0578613a , 785f23f01adfc8b64590050b160d342ab60605e9 , f4b6eea646e71a83010648582605dea70ec281f0 and 51f9fc0e6115d9f88b19300f65ec9866fba1a4bc implement this. There's more cleanup to be done in the compiler to replace paths with urls.
