### ISSUE TITLE
Dead link in Rust docs

### ISSUE THREAD

**Issue by tronical** [sixtyfpsui/sixtyfps#87]
https://www.sixtyfps.io/docs/rust/sixtyfps/langref/index.html has a dead link to https://www.sixtyfps.io/docs/rust/sixtyfps/langref/builtin_elements.md

**Comment by ogoffart** [comment]
I don't know how to fix that. The links are relative for the markdown on GitHub. If we want to include that in the rust doc we need to do some processing with a macro or something. Or maybe some JavaScript to fix up the links afterwards?

**Comment by tronical** [comment]
I like the JavaScript idea. These are unresolved links, so they are anchors with a "foo.md" href. So it might not be difficult to fix those on the fly.
