### ISSUE TITLE
opacity within a `for` messes up the size

### ISSUE THREAD

**Issue by Futsch1** [sixtyfpsui/sixtyfps#915]
Starting with sixtyfps v0.1.6, images in a certain part of my GUI are no longer resized but instead always shown with their full size. This is the affected .60 snippet:

```
ScrollView {
padding: 0px;
viewport-height: 100px;
height: similar-images-model.length > 1 ? 125px : 0px;
visible: similar-images-model.length > 1;

HorizontalBox { 
    alignment: start;
for item[i] in similar-images-model:
    Image {
        source: item.image;
        opacity: item.take-over ? 1.0 : 0.2;
        image-fit: contain;
        width: 180px;
        height: 100px;
        TouchArea { 
            clicked => {
                current-image.image = item.image;
                current-image.take-over = item.take-over;
                current-image.text = item.text;
                current-image.local-index = item.local-index;
            }
        }
        if (item.local-index == current-image.local-index) : Rectangle { opacity: 0.4; background: blue;}
    }
}
```

That's how it looks with v0.1.5:
![Screenshot from v0.1.5](https://user-images.githubusercontent.com/63090558/152656690-dd9c9ce2-0f15-428f-bbcb-bc5e4162a495.png)

And here with v0.1.6
![Screenshot from v0.1.6](https://user-images.githubusercontent.com/63090558/152656691-c72d1331-dc71-426e-b0a7-cacbcbccf398.png)

I was not yet able to create a minimum example to narrow it down.

**Comment by ogoffart** [comment]
I can't think on top of my head of anything that should cause this regression.  I'll have to investigate.

**Comment by ogoffart** [comment]
Ok, i made a small testcase:

```js
export Demo := Window {
    height: 100px;
    HorizontalLayout {
        for i in 32:
        Image {
            width: 30px;
            source: @image-url("https://sixtyfps.io/resources/logo_scaled.png");
            // comment this line to "fix" problem
            opacity: touch.pressed ? 0.5 : 1;
            touch := TouchArea {}
        }
    }
}
```
[Online Editor link](https://sixtyfps.io/releases/0.1.6/editor/?snippet=%0Aexport+Demo+%3A%3D+Window+%7B%0A++++height%3A+100px%3B%0A++++HorizontalLayout+%7B%0A++++++++for+i+in+32%3A%0A++++++++Image+%7B%0A++++++++++++width%3A+30px%3B%0A++++++++++++source%3A+%40image-url%28%22https%3A%2F%2Fsixtyfps.io%2Fresources%2Flogo_scaled.png%22%29%3B%0A++++++++++++%2F%2F+comment+this+line+to+%22fix%22+problem%0A++++++++++++opacity%3A+touch.pressed+%3F+0.5+%3A+1%3B%0A++++++++++++touch+%3A%3D+TouchArea+%7B%7D%0A++++++++%7D%0A++++%7D%0A%7D%0A)

This seems to be cause by the opacity.  Internally, adding an opacity adds a node in the scene graph, and i think that there must be a bug in the dimension tracking.

**Comment by ogoffart** [comment]
Note: this only happens if the element with opacity is the one in a `for`. It is possible to workaround the prolem by adding an intermediate Rectangle in the `for` like so:
```js
for item[i] in similar-images-model: Rectangle {
                                   // ^^^^^^^^ added Rectangle here
    width: 180px;
    height: 100px;
    Image {
        width: 100%;
        height: 100%;
        source: item.image;
        opacity: item.take-over ? 1.0 : 0.2;
        image-fit: contain;
        TouchArea { 
            clicked => {
                current-image.image = item.image;
                current-image.take-over = item.take-over;
                current-image.text = item.text;
                current-image.local-index = item.local-index;
            }
        }
        if (item.local-index == current-image.local-index) : Rectangle { opacity: 0.4; background: blue;}
    }
  }

```

**Comment by ogoffart** [comment]
But thanks for the bug report, we'll be working on a fix.
