### ISSUE TITLE
Expanding a ListView scrolled to the bottom doesn't scroll up

### ISSUE THREAD

**Issue by nyanpasu64** [sixtyfpsui/sixtyfps#93]
- Open the gallery sample app.
- Scroll the ListView down.
- Make the window taller.

The ListView scrollbar handle expands and disappears, but the ListView is still scrolled down (shows empty space below, and cuts off the top elements).

**Comment by ogoffart** [comment]
Thank you for trying and reporting bug.
It should be fixed now.
